import Header from "@/components/Header"; //component
import "./globals.css";
import { JetBrains_Mono } from "next/font/google"; // Correct import
import PageTransition from "@/components/PageTransition";
import StairTransition from "@/components/StairTransition";

// Assign the font to a constant at the module scope
const jetBrainsMono = JetBrains_Mono({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
  variable: "--font-jetbrainsMono", // Variable for the custom property
});

export const metadata = {
  title: "My Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* Apply the font variable to the body */}
      <body className={jetBrainsMono.variable}>
        <Header/>
        <StairTransition/>
        <PageTransition>{children}</PageTransition>
      </body>
    </html>
  );
}
